package com.github.bomiyr.runtimeconfig

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import java.io.FileWriter

/**
 * Task for RuntimeConfig class generation.
 */
abstract class RuntimeConfigTask : DefaultTask() {

    @get:Input
    abstract val fields: MapProperty<String, String>

    @get:Input
    abstract val classPackage: Property<String>

    @get:Input
    abstract val className: Property<String>

    @get:Input
    abstract val classModifier: Property<String>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun action() {

        val file = outputFile.asFile.get()

        file.parentFile.mkdirs()
        FileWriter(file).use { writer ->
            writer.write("// This file is generated by RuntimeConfig plugin. Do not modify\n\n")
            writer.write("package ${classPackage.get()}\n\n")
            writer.write("${classModifier.get()} object ${className.get()} {\n")
            fields.get().forEach { (key, value) ->
                writer.write("\tval $key = $value\n")
            }
            writer.write("}\n")
        }
    }
}